### ISSUE TITLE
Create UI field input types

### ISSUE THREAD

**Issue by antegadzo** [2sic/eav-item-dialog-angular#11]
## I'm submitting a ...

[x] action / task

## ...about

[x] edit experience / UI

## Task / Action Summary

Create field input types for formly form.
Update wiki documenting input fields features (one at a time).

## Steps to implement

* [x] create `string-default` input type and update wiki documentation if needed
* [x] create `string-url-path` input type and update wiki documentation if needed
* [x] create `string-dropdown` input type and update wiki documentation if needed
* [x] create `boolean-default` input type and update wiki documentation if needed
* [x] create `string-font-icon-picker` input type and update wiki documentation if needed
* [x] create `number-default` input type and update wiki documentation if needed
* [x] create `datetime-default` input type and update wiki documentation if needed
* [x] create `empty-default` input type and update wiki documentation if needed
* [x] create `entity-default` input type and update wiki documentation if needed
