### ISSUE TITLE
Create form builder prototype module with reactive forms instead Formly.

### ISSUE THREAD

**Issue by antegadzo** [2sic/eav-item-dialog-angular#12]
## I'm submitting a ...

[x] action / task

## ...about

[x] edit experience / UI

## Task / Action Summary
Create form builder module for reactive forms for Eav Item dialog. The builder needs to add input controls dynamically. Reactive forms need to communicate with NGRX store. The builder needs adding input types with wrappers. Input types need to have a built-in configuration.

## Steps to implement

* [x] Create prototype form builder
* [x] Create functionality for wrappers
* [x] Move configuration in input types
* [x] Add already created input types

**Comment by aitboudad** [comment]
hi, I'm maintaining `ngx-formly` and I want to know if is there anything wrong with formly and we should improve, thanks!

**Comment by iJungleboy** [comment]
@aitboudad basicaly we wanted to use formly first, but when using a reactive model and rx/store, it was basically impossible. the entire binding mechanisms etc. were just not meant for it, because formly is 2 way binding.

**Comment by aitboudad** [comment]
that's true, but we mainly based on reactive form so I think it's not a big deal.
anyway thanks and not forget that suggestions and PRs are welcomed :).
