### ISSUE TITLE
Unable to change values in default language

### ISSUE THREAD

**Issue by PagnoDunadan** [2sic/eav-item-dialog-angular#139]
## I'm submitting a ...

[x] action / task

## ...about

[x] edit experience / UI

## Task / Action Summary
Unable to change values in default language when language is set to some other than default when creating new items. Also, that language shouldn't be translatable.

Default language: de-de
DNN switched language: en-us

**2sxc 10:**
![2019-10-30 15_40_58-Home](https://user-images.githubusercontent.com/7113033/67868133-c774d900-fb2b-11e9-9915-e42f1c00a51b.png)

**2sxc 9:**
![2019-10-30 15_41_20-Home](https://user-images.githubusercontent.com/7113033/67868149-cd6aba00-fb2b-11e9-8412-29bab8cb99e1.png)

## Steps to implement

* [x] Disable translations when default language has no value
* [x] Enable default language values change
* [x] Switch to default language on form start up when items miss values in default language
