### ISSUE TITLE
Add new root for the project

### ISSUE THREAD

**Issue by PagnoDunadan** [2sic/eav-item-dialog-angular#167]
## I'm submitting a ...

[x] action / task

## ...about

[x] edit experience / UI

## Task / Action Summary
Add new root for the project, the app.module which includes ui.html, initial factory to read params from the url and root routes definition

## Steps to implement

* [ ] Create eav-dialogs-root project
* [ ] Create ui.html and adjust build helpers
* [ ] Create initializer factory
* [ ] Define routes to ng-dialogs and edit-ui
