### ISSUE TITLE
Create ADAM (Automatic Digital Assets Manager)

### ISSUE THREAD

**Issue by antegadzo** [2sic/eav-item-dialog-angular#20]
## I'm submitting a ...

[x] action / task

## Task / Action Summary

ADAM (Automatic Digital Assets Manager)

## Steps to implement

* [x] Adam foders functionality
* [x] Adam files functionality
* [x] Dropzone - dropping files
