### ISSUE TITLE
Hyperlink-default / library input types

### ISSUE THREAD

**Issue by antegadzo** [2sic/eav-item-dialog-angular#21]
## I'm submitting a ...

[x] action / task

## ...about

[x] edit experience / UI

## Task / Action Summary

Finish hyperlink-default and hyperlink-library input types

## Steps to implement

* [x] Hyperlink-default input type
* [x] Attach Adam to the hyperlink-default input type (upload, image manager,  document manager)
* [x] Attach pagePicker
* [x] Hyperlink-library (file library) input type
