### ISSUE TITLE
Implement classes for items and content types for the the existing V1 JSON object format

### ISSUE THREAD

**Issue by iJungleboy** [2sic/eav-item-dialog-angular#3]
## I'm submitting a ... 
[x] action / task

## ...about   
[x] edit experience / UI  

## Task / Action Summary

To keep things simple, we want to use a memory object model for items and content-types which is very similar, if not the same, as the V1 json format in 2sxc. See https://github.com/2sic/2sxc/wiki/Format-json-v1

This is step 1, where we simply enable loading of this data - internally the data will look a bit different when working with it. Note: as this is version 1, and we want to be sure this is clear, the classes should all end with the number 1

## Steps to implement
* [x] Create the wrapper class `JsonPackage1` (which has the header `JsonHeader`and one entity or contenttype
* [x] create the item class `JsonItem1` to represent the https://github.com/2sic/2sxc/wiki/Format-json-v1-entity
* [x] create a content type class `JsonContentType1` to represent https://github.com/2sic/2sxc/wiki/Format-json-v1-content-type
* [x] create a loader or similar which loads format json object into this schema
* [x] create ca. 20 tests to validate this loader
