### ISSUE TITLE
Implement in-store data model for items (entities)

### ISSUE THREAD

**Issue by iJungleboy** [2sic/eav-item-dialog-angular#4]
## I'm submitting a ... 
[x] action / task

## ...about   
[x] edit experience / UI  

## Task / Action Summary

Create the in-memory model for items. It's similar to #3, but still a bit different. Two core differences:

1. in-memory model is more complex, because we want to use typed objects as we're working
1. in-memory model will have values which in json are like this: `{ "*": "value" }` but in the memory model it's actually a more complex `EavValue` object like `{ Value: "value", Dimensions: [] }` because the key in the json format is actually a language-assignment, which can be multiple dimensions. If you don't understand this yet, don't worry, just give it empty Dimensions [] for now. I'll help with the details later on. 

## Steps to implement
* [x] create the core classes `EavEntity`, `EavAttribute`,  `EavValue`, and additional helpers as needed 
* [x] Create the typed attribute and value classes `EavAttribute<T> inheriting EavAttribute`, `EavValue<T> inheriting EavValue` - note that the `<T>` is necessary because there will be lists of EavAttributes, but once this is used somewhere it will probably be treated as an EavAttribute<string> or EavAttribute<number> to make sure it's typed
* [x] Create object builder code which create such an object, mostly from the in-memory definitions of #3 
* [x] create ca. 20 tests to validate / proof this object loader
* [x] add this to the ngrx store, so this is the format delivered by the `items` array
* [x] create 2 -10 tests for the ngrx store implementation
