### ISSUE TITLE
Implement in-store classes for contentTypes

### ISSUE THREAD

**Issue by iJungleboy** [2sic/eav-item-dialog-angular#5]
## I'm submitting a ... 
[x] action / task

## ...about   
[x] edit experience / UI  

## Task / Action Summary

Similar to #4, make sure that also content-type definitions have a typed definition in memory. Note that many inner things (metadata) are also entities. 

## Steps to implement
* [x] Create the core classes like `ContentTypeDef`, `AttributeDef` etc. 
* [x] create loader / builder code to initialize them from a JSON V1 format
* [x] create ca. 20 tests to test the loader / builder
* [x] implement in ngrx store
* [x] create 2-10 tests to validate the ngrx-store
