### ISSUE TITLE
Switch icons to only use google material from + 2-3 custom svg

### ISSUE THREAD

**Issue by iJungleboy** [2sic/eav-item-dialog-angular#70]
## Task / Action Summary

We want to drop our custom icon library and try to use the material icons from CDN

## Steps to implement

* [x] Ensure material icons are loaded from CDN (probably already happens)
* [x] Remove the current font-icons (css and font-files)
* [x] review the app - find missing icons, update to use material

Note: if any icon is special and shouldn't use material, make a list so we can design them asap
