### ISSUE TITLE
Upgrade TinyMCE to v5

### ISSUE THREAD

**Issue by PagnoDunadan** [2sic/eav-item-dialog-angular#96]
## I'm submitting a ...

[x] action / task

## ...about

[x] edit experience / UI

## Task / Action Summary
Upgrade TinyMCE to version 5. Make sure custom toolbar buttons work.

## Steps to implement

* [x] Upgrade TinyMCE to v5
* [x] Update tinymce-angular package
* [x] Fix toolbar buttons configuration
* [x] Fix icons for toolbar buttons
* [x] Fix CSS
