### ISSUE TITLE
Migrate to ngrx-data

### ISSUE THREAD

**Issue by PagnoDunadan** [2sic/eav-item-dialog-angular#97]
## I'm submitting a ...

[x] action / task

## ...about

[x] edit experience / UI

## Task / Action Summary
Migrate features part of the store to ngrx-data

## Steps to implement

* [x] Migrate features part of the store store to ngrx-data
* [x] Migrate languages part of the store store to ngrx-data
* [x] Migrate input types part of the store store to ngrx-data
* [x] Migrate content types part of the store store to ngrx-data
